name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'csharp'

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 3.1.x

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.x

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test v8
        run: dotnet test ./tests/GeneratedEntityFramework.Tests.v8/GeneratedEntityFramework.Tests.v8.csproj --configuration Release --no-build --verbosity normal --framework net8.0

      - name: Test v7
        run: dotnet test ./tests/GeneratedEntityFramework.Tests.v7/GeneratedEntityFramework.Tests.v7.csproj --configuration Release --no-build --verbosity normal --framework net7.0

      - name: Test v6
        run: dotnet test ./tests/GeneratedEntityFramework.Tests.v6/GeneratedEntityFramework.Tests.v6.csproj --configuration Release --no-build --verbosity normal --framework net6.0

      - name: Test v5
        run: dotnet test ./tests/GeneratedEntityFramework.Tests.v5/GeneratedEntityFramework.Tests.v5.csproj --configuration Release --no-build --verbosity normal --framework net5.0

      - name: Test v3
        run: dotnet test ./tests/GeneratedEntityFramework.Tests.v3/GeneratedEntityFramework.Tests.v3.csproj --configuration Release --no-build --verbosity normal --framework netcoreapp3.1

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
